apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: ">=1.0.0-alpha"
  test:
    enable: false
  values:
    ingress:
      hosts:
        - host: ad4c52dff457b4585a04caec0c578cc3-991302792.eu-central-1.elb.amazonaws.com
          paths:
            - path: /
              pathType: ImplementationSpecific
