apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: "6.0.3"
  test:
    enable: false
  values:
    ui:
      color: "#ff577c"
    ingress:
      hosts:
        - host:
          paths:
            - path: /
              pathType: ImplementationSpecific
