apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: "6.0.2"
  test:
    enable: false
  values:
    ui:
      color: "#34577c"
    ingress:
      hosts:
        - host: ''
          paths:
            - path: /
              pathType: ImplementationSpecific
